Repository shawntz/eyeris, pull requests merged in 2025-06, with the labels that each got.

#166 Fixed edge case in bidsify epoch plotting
  R/pipeline-bidsify.R
Labels: bug

#168 fixed multi-block epoch bug
  R/pipeline-epoch.R
Labels: bug

#169 feat/detrend plots refactor (and fix #165)
  Makefile
  NAMESPACE
  R/eyeris-package.R
  R/pipeline-bidsify.R
  R/pipeline-detrend.R
  R/pipeline-glassbox.R
  R/plot.eyeris.R
  R/utils-render_report.R
  man/figures/README-timeseries-plot-2.png
  man/figures/README-unnamed-chunk-3-1.png
  man/plot.eyeris.Rd
  man/plot_detrend_overlay.Rd
Labels: bug, feature

#171 NF: `eyelogger()`
  NAMESPACE
  R/utils-eyelogger.R
  _pkgdown.yml
  man/eyelogger.Rd
  man/plot.eyeris.Rd
  man/plot_detrend_overlay.Rd
Labels: feature, assigned

#172 release/v1.2.1
  CRAN-SUBMISSION
  DESCRIPTION
  NEWS.md
  README.Rmd
  README.md
  _pkgdown.yml
  cran-comments.md
Labels: assigned, CRAN RELEASE

#178 NF: #173 confounds file
  NAMESPACE
  R/eyeris-package.R
  R/pipeline-bidsify.R
  R/pipeline-confounds.R
  R/pipeline-epoch.R
  R/pipeline-glassbox.R
  R/zzz.R
  README.md
  _pkgdown.yml
  man/calc_euclidean_dist.Rd
  man/calculate_epoched_confounds.Rd
  man/export_confounds_to_csv.Rd
  man/get_confounds_for_step.Rd
  man/normalize_gaze_coords.Rd
  man/summarize_confounds.Rd
  man/tag_blinks.Rd
  man/tag_gaze_coords.Rd
Labels: feature, assigned

#177 BF: #175 (baseline epoching)
  DESCRIPTION
  NEWS.md
  R/pipeline-bidsify.R
  R/pipeline-epoch.R
  R/utils-baseline.R
  R/utils-checks.R
  _pkgdown.yml
  man/epoch.Rd
  man/find_baseline_structure.Rd
Labels: bug, assigned, breaking-change

#185 Enh/174
  R/pipeline-bidsify.R
  man/bidsify.Rd
Labels: feature, assigned, breaking-change

#203 FF: #200 fix `run_num` override arg in `bidsify()`
  R/pipeline-bidsify.R
  R/utils-render_report.R
  man/bidsify.Rd
Labels: bug, chore, assigned

#207 FF: add validation for `prev_op` in `zscore_pupil()` function
  R/pipeline-zscore.R
Labels: bug, assigned, breaking-change, enhancement

#209 FF: track pipeline step provenance and improve error handling
  R/pipeline-bin.R
  R/pipeline-deblink.R
  R/pipeline-detransient.R
  R/pipeline-detrend.R
  R/pipeline-downsample.R
  R/pipeline-epoch.R
  R/pipeline-glassbox.R
  R/pipeline-handler.R
  R/pipeline-interpolate.R
  R/pipeline-lpfilt.R
  R/pipeline-zscore.R
  R/utils-parsers.R
  R/utils-render_report.R
  man/bin.Rd
  man/deblink.Rd
  man/detransient.Rd
  man/detrend.Rd
  man/downsample.Rd
  man/epoch.Rd
  man/interpolate.Rd
  man/lpfilt.Rd
  man/pipeline_handler.Rd
  man/zscore.Rd
  vignettes/custom-extensions.Rmd
Labels: bug, docs, assigned, breaking-change, enhancement
